server:  
  port: ${PORT:3333}
  ssl:
    key-store: keystore.jks
    key-store-password: password
    key-password: password

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:https://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true