info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account: 
      path: /account/**
      serviceId: account-service
    customer:
      path: /customer/**
      serviceId: customer-service          

ribbon:
  eureka:
    enabled: true
  TrustStore: keystore.jks
  TrustStorePassword : password
  ReadTimeout: 60000
  IsSecure: true
  MaxAutoRetries: 1

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765
  ssl:
    key-store: keystore.jks
    key-store-password: password
    key-password: password

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG